#!/bin/bash
set -e
exec > >(tee /var/log/user-data.log)
exec 2>&1

echo "=== Starting EC2 initialization ==="

# ---- System Prep ----
yum update -y
yum install -y git jq awscli gcc openssl-devel bzip2-devel libffi-devel make unzip zip

# ---- Install Python 3.12 ----
dnf install -y python3.12 python3.12-devel
ln -sf /usr/bin/python3.12 /usr/local/bin/python3
python3 --version

# ---- Install Poetry 1.3.2 ----
curl -sSL https://install.python-poetry.org | python3 -
export PATH="/root/.local/bin:$PATH"
poetry --version

# ---- Install Node.js (for demo web app) ----
curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -
yum install -y nodejs

# ---- Simple Node.js web app ----
mkdir -p /opt/webapp
cd /opt/webapp
cat > server.js <<'EOFSERVER'
const http = require('http');
const PORT = 80;
http.createServer((req,res)=>{
  res.writeHead(200, {'Content-Type':'text/plain'});
  res.end('EC2 + Temporal Cloud Demo running\n');
}).listen(PORT,()=>console.log('Server running on '+PORT));
EOFSERVER

cat > package.json <<'EOFPACKAGE'
{"name":"ec2-s3-webapp","version":"1.0.0","main":"server.js","scripts":{"start":"node server.js"}}
EOFPACKAGE

npm install

cat > /etc/systemd/system/webapp.service <<EOFSERVICE
[Unit]
Description=EC2 Web Application
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=/opt/webapp
ExecStart=/usr/bin/node server.js
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOFSERVICE

systemctl daemon-reload
systemctl enable webapp
systemctl start webapp

# ---- Setup Temporal Order Management Worker ----
echo "=== Setting up Temporal Order Management Worker ==="

mkdir -p /opt/temporal-order-worker/certs
cd /opt/temporal-order-worker

# --- Hard-coded AWS Region ---
AWS_REGION="us-east-1"
echo "Using hard-coded AWS region: $AWS_REGION"

# --- Fetch Temporal Cloud credentials from AWS Secrets Manager ---
SECRET_NAME="temporal-cloud-credentials"
echo "Fetching Temporal Cloud credentials from Secrets Manager..."
aws secretsmanager get-secret-value \
  --secret-id "$SECRET_NAME" \
  --region "$AWS_REGION" \
  --query SecretString \
  --output text > secret.json

NAMESPACE=$(jq -r '.namespace' secret.json)
ADDRESS=$(jq -r '.address' secret.json)
CERT=$(jq -r '.cert' secret.json)
KEY=$(jq -r '.key' secret.json)

echo "$CERT" | base64 -d > /opt/temporal-order-worker/certs/client.pem
echo "$KEY" | base64 -d > /opt/temporal-order-worker/certs/client.key
rm -f secret.json

# --- Environment vars aligned with setcloudenv.sh ---
cat > /opt/temporal-order-worker/worker.env <<EOF
TEMPORAL_NAMESPACE=$NAMESPACE
TEMPORAL_ADDRESS=$ADDRESS
TEMPORAL_CERT_PATH=/opt/temporal-order-worker/certs/client.pem
TEMPORAL_KEY_PATH=/opt/temporal-order-worker/certs/client.key
EOF

# --- Clone the Temporal Order Management Demo ---
git clone https://github.com/temporal-sa/temporal-order-management-demo.git repo || true
cd repo/python

# --- Copy and activate example setcloudenv.sh ---
cat > ../setcloudenv.sh <<EOF
#!/bin/sh
# Auto-generated by user-data.sh at boot
export TEMPORAL_ADDRESS=$ADDRESS
export TEMPORAL_NAMESPACE=$NAMESPACE
export TEMPORAL_CERT_PATH=/opt/temporal-order-worker/certs/client.pem
export TEMPORAL_KEY_PATH=/opt/temporal-order-worker/certs/client.key
export TEMPORAL_TASK_QUEUE=orders
export TEMPORAL_NEXUS_TASK_QUEUE=shipping
export TEMPORAL_NEXUS_SHIPPING_ENDPOINT=shipping-endpoint
EOF

chmod +x ../setcloudenv.sh
chmod +x ./startcloudworker.sh

# --- Install dependencies with Poetry ---
poetry env use /usr/bin/python3.12
poetry install --no-root

# --- Create systemd service for Temporal Python worker ---
cat > /etc/systemd/system/temporal-worker.service <<EOF
[Unit]
Description=Temporal Order Management Python Worker
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=/opt/temporal-order-worker/repo/python
EnvironmentFile=/opt/temporal-order-worker/worker.env
ExecStart=/root/.local/bin/poetry run bash -lc "./startcloudworker.sh"
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable temporal-worker
systemctl start temporal-worker

echo "=== Initialization complete! ==="
echo "Node.js app running on port 80 and Temporal worker connected to Temporal Cloud."